#!/bin/sh
#
# Copyright (c) 2009 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

NSS_FILES="libnspr4.so.0d libplds4.so.0d libplc4.so.0d libssl3.so.1d \
    libnss3.so.1d libsmime3.so.1d libnssutil3.so.1d"

remove_nss_symlinks() {
  for f in $NSS_FILES
  do
    rm -rf "/opt/brackets/$f"
  done
}

remove_nss_symlinks

rm -rf "/opt/brackets/libudev.so.0"
